plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tf.clasificacioncutter'
    compileSdk 37

    defaultConfig {
        applicationId "com.tf.clasificacioncutter"
        minSdk 23
        targetSdk 37
        versionCode 11
        versionName "1.1.4"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        viewBinding true
    }

    testOptions {
        unitTests.includeAndroidResources = true
    }

    configurations {
        configureEach {
            exclude module: 'commons-logging'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    // Kotlin
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"

    // AndroidX
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.core:core-ktx:1.19.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.2'

    // Google & Material
    implementation 'com.google.android.material:material:1.14.0'

    // Third party
    implementation 'com.opencsv:opencsv:5.12.0'

    // Testing
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.7.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
}
